# Generated by Django 5.2.8 on 2025-11-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_blog_author_fk'),
        ('main', '0006_alter_menuitem_options_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to='main.attachment'),
        ),
    ]
