# Generated by Django 5.2.8 on 2025-11-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_menuitem_url_menuitem_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta',
            field=models.TextField(default='{}', max_length=1000, verbose_name='meta'),
        ),
    ]
