# Generated by Django 5.2.8 on 2025-11-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_page_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='page',
            new_name='page_fk',
        ),
    ]
