# Generated by Django 5.2.8 on 2025-11-20 14:12

import casino.storages
import django.db.models.deletion
import django_minio_backend.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_rename_page_menuitem_page_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=casino.storages.PublicStorage(), upload_to=django_minio_backend.models.iso_date_prefix)),
                ('is_public', models.BooleanField(default=True)),
                ('filesize', models.BigIntegerField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='main_attach_content_dbeb5e_idx')],
            },
        ),
    ]
