# Generated by Django 5.2.8 on 2025-12-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_typemenuitem_alter_page_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type_menu_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typemenuitem', verbose_name='Тип меню'),
        ),
    ]
