# Generated by Django 5.2.8 on 2025-11-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='category_fk',
        ),
    ]
