# Generated by Django 5.2.8 on 2025-11-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_category_game_category_fk'),
        ('main', '0006_alter_menuitem_options_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.AddField(
            model_name='game',
            name='image_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_image', to='main.attachment'),
        ),
    ]
