# Generated by Django 5.2.8 on 2025-11-27 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_image_game_image_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=350)),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('game_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='game.game')),
            ],
            options={
                'verbose_name': 'Конфигурация игры',
                'verbose_name_plural': 'Конфигурации игр',
            },
        ),
    ]
