# Generated by Django 5.2.8 on 2025-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameconfig',
            unique_together={('game_fk', 'key')},
        ),
    ]
