# Generated by Django 5.2.8 on 2025-11-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gameconfig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='game_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='game.game'),
        ),
    ]
