# Generated by Django 5.2.8 on 2025-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gameconfig_game_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичный ключ'),
        ),
    ]
