# Generated by Django 5.2.8 on 2025-11-28 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameconfig_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvablyFairChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_seed', models.CharField(max_length=128)),
                ('server_seed_hash', models.CharField(db_index=True, max_length=128)),
                ('client_seed', models.CharField(blank=True, max_length=128)),
                ('nonce_start', models.BigIntegerField(default=0)),
                ('nonce_end', models.BigIntegerField(default=0)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provably Fair Chain',
                'verbose_name_plural': 'Provably Fair Chains',
                'indexes': [models.Index(fields=['user_fk', '-created_at'], name='game_provab_user_fk_63ed2d_idx'), models.Index(fields=['server_seed_hash'], name='game_provab_server__48fcb2_idx')],
                'unique_together': {('user_fk', 'server_seed_hash')},
            },
        ),
    ]
