# Generated by Django 5.2.8 on 2025-11-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_provablyfairchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provablyfairchain',
            name='nonce_end',
        ),
        migrations.RemoveField(
            model_name='provablyfairchain',
            name='nonce_start',
        ),
    ]
