# Generated by Django 5.2.8 on 2025-11-30 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_provablyfairchain_nonce_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.BigIntegerField(db_index=True, default=0, help_text='Порядковый номер игры в текущей цепочке (начинается с 0)')),
                ('bet_amount', models.DecimalField(decimal_places=8, help_text='Сумма ставки в выбранной валюте', max_digits=20)),
                ('payout', models.DecimalField(decimal_places=8, default=0, help_text='Выплата (0 если проигрыш)', max_digits=20)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, help_text='Множитель (например 2.00x)', max_digits=10, null=True)),
                ('win', models.BooleanField(db_index=True, default=False)),
                ('game_data', models.JSONField(default=dict, help_text='Выбор игрока, результат, стрик и т.д.')),
                ('game_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game')),
                ('pf_chain_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pf_chain_fk_game_history', to='game.provablyfairchain')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История игры',
                'verbose_name_plural': 'История игр',
                'indexes': [models.Index(fields=['user_fk', '-created_at'], name='game_gamehi_user_fk_6b6c43_idx'), models.Index(fields=['pf_chain_fk', 'nonce'], name='game_gamehi_pf_chai_b13170_idx'), models.Index(fields=['win', '-created_at'], name='game_gamehi_win_9a6699_idx'), models.Index(fields=['-created_at'], name='game_gamehi_created_499fc0_idx')],
                'unique_together': {('pf_chain_fk', 'nonce')},
            },
        ),
    ]
