# Generated by Django 5.2.8 on 2025-11-30 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamehistory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='gamehistory',
            constraint=models.UniqueConstraint(fields=('user_fk', 'pf_chain_fk', 'nonce'), name='unique_game_per_nonce'),
        ),
    ]
