# Generated by Django 5.2.8 on 2025-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamehistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
