# Generated by Django 5.2.8 on 2025-12-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_code'),
        ('user', '0008_rename_currency_userbalance_currency_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='currency_fk',
            field=models.ForeignKey(default=1, help_text='Валюта', on_delete=django.db.models.deletion.CASCADE, to='user.currency'),
            preserve_default=False,
        ),
    ]
