# Generated by Django 5.2.8 on 2025-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gamehistory_currency_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='payout',
            field=models.DecimalField(decimal_places=8, help_text='Выплата (0 если проигрыш)', max_digits=20),
        ),
    ]
