# Generated by Django 5.2.8 on 2025-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_gamehistory_payout'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamehistory',
            name='game_gamehi_win_9a6699_idx',
        ),
        migrations.RemoveField(
            model_name='gamehistory',
            name='win',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='game_status',
            field=models.CharField(choices=[('ongoing', 'Ожидание'), ('win', 'Победа'), ('lose', 'Проигрыш')], db_index=True, default='ongoing', max_length=10),
        ),
    ]
