# Generated by Django 5.2.8 on 2025-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_gamehistory_game_gamehi_win_9a6699_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_status',
            field=models.CharField(choices=[('ongoing', 'Ожидание'), ('win', 'Победа'), ('lose', 'Проигрыш'), ('push', 'Ничья')], db_index=True, default='ongoing', max_length=10),
        ),
    ]
