# Generated by Django 5.2.8 on 2025-12-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gamehistory_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='game_status',
            field=models.CharField(choices=[('ongoing', 'Ожидание'), ('win', 'Победа'), ('lose', 'Проигрыш'), ('draw', 'Ничья')], db_index=True, default='ongoing', max_length=10),
        ),
    ]
