# Generated by Django 5.2.8 on 2025-12-22 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gamehistory_game_status'),
        ('user', '0010_currency_balance_decimal_places_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='gamehistory',
            index=models.Index(fields=['game_fk', '-payout'], name='game_gamehi_game_fk_c2e4f7_idx'),
        ),
    ]
