# Generated by Django 5.2.8 on 2025-12-22 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_code_and_more'),
        ('user', '0010_currency_balance_decimal_places_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamehistory',
            index=models.Index(fields=['game_fk', '-multiplier'], name='game_gamehi_game_fk_bf08c9_idx'),
        ),
    ]
