# Generated by Django 5.2.8 on 2026-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_gamehistory_game_gamehi_game_fk_bf08c9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='value',
            field=models.TextField(max_length=6000),
        ),
    ]
