# Generated by Django 5.2.8 on 2025-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_demo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
