# Generated by Django 5.2.8 on 2025-11-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_balance_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='balance_usd',
        ),
    ]
