# Generated by Django 5.2.8 on 2025-12-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
    ]
