# Generated by Django 5.2.8 on 2025-12-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='currency',
            new_name='currency_fk',
        ),
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('user_fk', 'currency_fk')},
        ),
    ]
