# Generated by Django 5.2.8 on 2025-12-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_currency_userbalance_currency_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance_demo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance_usd',
        ),
    ]
