# Generated by Django 5.2.8 on 2025-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_balance_demo_remove_user_balance_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='balance_decimal_places',
            field=models.PositiveBigIntegerField(default=2, verbose_name='Знаков после точки в балансе'),
        ),
        migrations.AddField(
            model_name='currency',
            name='payout_decimal_places',
            field=models.PositiveBigIntegerField(default=2, verbose_name='Знаков после точки при куше'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
    ]
