# Generated by Django 5.2.8 on 2025-12-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menuitem_type_menu_fk'),
        ('user', '0010_currency_balance_decimal_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.attachment', verbose_name='Аватар'),
        ),
    ]
