# Generated by Django 5.2.8 on 2025-12-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menuitem_type_menu_fk'),
        ('user', '0011_user_avatar_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='main.attachment'),
        ),
    ]
